const ADMIN_COOKIE = "AdminRefresh";
const USER_COOKIE = "jwt";
const INVOICE_EXPIRATION_TIME = 24;
const NEXT_ITEMS_FEES = 7;

export { ADMIN_COOKIE, USER_COOKIE,INVOICE_EXPIRATION_TIME,NEXT_ITEMS_FEES };
